/* The Claim Crucible — case data (browser global mirror of case.json).
 * Every factual statement is tied to a source ID (S01–S20) or labelled
 * INFERRED / UNRESOLVED. See case.json for the machine-readable twin and
 * _test/claim-crucible-test.js for the mechanical equivalence check.
 */
"use strict";
window.CASE_DATA = {
  "claim": {
    "text": "Project Looking Glass was a genuine United States government program or device used to observe probable future timelines."
  },

  "verdict": {
    "label": "Contradicted",
    "confidence_label": "medium",
    "confidence_pct": 62,
    "explanation": "As literally stated — a U.S. government \u201cProject Looking Glass\u201d device that observes probable future timelines — the claim is contradicted by the official record. The only genuine U.S. program that carries the name \u201cLooking Glass\u201d is the airborne nuclear command-and-control post (SAC EC-135, 1961\u20131998; then the Navy E-6B; now a planned \u201cLooking Glass-Next\u201d), whose documented function is continuity of nuclear command, control, and communications — not observing the future. No official, archival, FOIA, court, or primary record of a future-time-viewing \u201cLooking Glass\u201d device exists in the searched record, and the distinctive \u201cprobable future timelines\u201d wording traces verbatim to a single self-described whistleblower\u2019s testimony (Dan Burisch) published by the paranormal-advocacy site Project Camelot \u2014 a witness whose account investigative journalist George Knapp has publicly described as an elaborate hoax. We do NOT assert the name \u201cLooking Glass\u201d is fake (it is real \u2014 as an airborne command post), nor that no classified program can ever have existed (absence of records cannot prove a negative). Confidence is medium because the archival-absence leg of the falsification is non-exhaustive and the hoax accusation is reported secondhand; if those caveats are weighted strictly the verdict could downgrade toward \u201cunsupported.\u201d"
  },

  "epistemic": {
    "observed": "Directly supported by a cited source in this file or by the executed checks (e.g., \u201cSAC began the Looking Glass airborne command post on 3 February 1961\u201d \u2014 source S02/S03).",
    "inferred": "Reasoned from observed evidence but not directly demonstrated (e.g., \u201cthe name collision with the real airborne command post is the most plausible origin of the myth\u201d \u2014 not shown by any single document).",
    "unresolved": "Insufficient or conflicting evidence (e.g., whether any fully classified facility named by the witness ever existed; whether the archival absence is complete)."
  },

  "epistemic_summary": [
    { "label": "OBSERVED", "kind": "observed", "body": "A real U.S. government program named \u201cLooking Glass\u201d existed, but it was the SAC/USSTRATCOM airborne nuclear command post (EC-135, later E-6B) \u2014 a communications and command-continuity aircraft with no time-viewing function (S02, S03, S06). Project Stargate was a real, declassified U.S. government remote-viewing (ESP) research program (1972\u20131995) judged a failure by an internal evaluation, unrelated to any future-time-viewing machine (S07, S08, S10). The wording \u201cprobable future timelines\u201d in the disputed claim appears verbatim on Project Camelot\u2019s T1v83 page relaying Dan Burisch\u2019s testimony (S11)." },
    { "label": "INFERRED", "kind": "inferred", "body": "The myth most plausibly arose from (a) the legitimate name collision \u2014 a real program already called \u201cLooking Glass\u201d \u2014 combined with (b) conflation with the real, now-famous Project Stargate ESP program, so a future-viewing device could be grafted onto genuine institutional name/aura (source-grounded reasoning, not shown by one document)." },
    { "label": "UNRESOLVED", "kind": "unresolved", "body": "Whether any fully secret facility described by the witness ever existed; whether the archival absence in public records is complete; whether the sole witness\u2019s claimed employment/credentials are verifiable (only third-hand negatives found). These do not add positive support for the device claim." }
  ],

  "subclaims": [
    { "text": "S1 \u2014 An official U.S. program named \u201cProject Looking Glass\u201d with a time-viewing function existed.", "status": "ambiguous", "supporting_sources": [], "challenging_sources": ["S02", "S03", "S06"], "settled_by": "A FOIA/declassified official document or a primary design/procurement record naming such a program with that function would substantiate it; none was found, and official histories show the name\u2019s only documented usage is the airborne command post." },
    { "text": "S2 \u2014 A similarly named but unrelated real program exists: the airborne nuclear command post.", "status": "support", "supporting_sources": ["S01", "S02", "S03", "S06", "S04"], "challenging_sources": [], "settled_by": "Observed via FAS, USAF/SAC histories, Arms Control Association, NYT 1965, STRATCOM, and NARA photo records; function is nuclear command-control-communications, not future viewing." },
    { "text": "S3 \u2014 The claim conflates Project Stargate (real remote-viewing ESP research) with Looking Glass.", "status": "support", "supporting_sources": ["S07", "S08", "S10"], "challenging_sources": [], "settled_by": "Stargate was a real declassified U.S. remote-viewing program (1972\u20131995) judged a failure, about trained viewers and distant/current targets \u2014 not a machine viewing future timelines; podcast lore merges the names." },
    { "text": "S4 \u2014 A physical device that displays/observes probable future timelines existed.", "status": "challenge", "supporting_sources": [], "challenging_sources": ["S02", "S03", "S13", "S11"], "settled_by": "No official, archival, FOIA, patent, or primary document supports such a device; the narrative traces to a single witness\u2019s unverified testimony whose account has been publicly called a hoax." },
    { "text": "S5 \u2014 Evidence exists that the U.S. observed probable future timelines.", "status": "challenge", "supporting_sources": [], "challenging_sources": ["S11", "S12", "S13"], "settled_by": "A controlled, replicable demonstration or verifiable predictive output would substantiate it; only uncorroborated testimony with circular \u201cconfirmation\u201d links exists." },
    { "text": "S6 \u2014 The principal story originated in UFO/paranormal lore and is amplified by entertainment media.", "status": "support", "supporting_sources": ["S11", "S12", "S14", "S15", "S16", "S17", "S18", "S19", "S20"], "challenging_sources": [], "settled_by": "The exact wording is traceable to Project Camelot\u2019s T1v83 page (Dan Burisch testimony), recycled across podcast and UFO-lore media with no primary documents." }
  ],

  "agreed_facts": [
    { "text": "There is a genuine, well-documented U.S. program named \u201cLooking Glass\u201d \u2014 the airborne nuclear command post \u2014 unrelated to any future-viewing device.", "cites": ["S01", "S02", "S03", "S06"] },
    { "text": "There is a genuine, declassified U.S. government remote-viewing research program, Project Stargate (1972\u20131995), which an internal review judged a failure and which concerned trained viewers, not a machine observing future timelines.", "cites": ["S07", "S08", "S10"] },
    { "text": "The distinctive phrase \u201cprobable future timelines\u201d from the disputed claim appears verbatim in Dan Burisch\u2019s testimony as published by Project Camelot.", "cites": ["S11"] },
    { "text": "No official, archival, FOIA, court, or primary record of a \u201cLooking Glass\u201d device that observes the future was found in the searched public record.", "cites": ["S05", "S09", "S10"] }
  ],

  "disputed_assertions": [
    { "text": "That a physical \u201cLooking Glass\u201d device at a facility like Area 51\u2019s \u201cS-4\u201d was used to view probable future timelines.", "cites": ["S11", "S12", "S13"] },
    { "text": "That the device\u2019s view of the future stopped at 2012, and related 2012-prophetic claims.", "cites": ["S15", "S18"] },
    { "text": "Whether the sole witness\u2019s identity, claimed credentials, and employment at S-4 can be verified (only third-hand negatives and a documented public hoax accusation exist).", "cites": ["S11", "S13"] }
  ],

  "contradictions": [
    { "text": "The name is real but not the function: official and reputable sources show \u201cLooking Glass\u201d = nuclear airborne command post, which is a communications/command aircraft \u2014 this directly contradicts the future-timeline-viewing device reading.", "cites": ["S02", "S03", "S06"] },
    { "text": "The claim\u2019s distinctive wording (\u201cprobable future timelines\u201d) is sourced to a single witness\u2019s uncorroborated testimony on a paranormal-advocacy site, yet the claim is often repeated as established government fact without any of that provenance.", "cites": ["S11", "S14"] },
    { "text": "Sympathetic UAP media themselves state the claims \u201cremain unverified\u201d and that no peer-reviewed or documentary record validates such a device \u2014 contradicting the claim\u2019s implicit assertion of a documented program.", "cites": ["S12", "S13"] },
    { "text": "Project Stargate (remote viewing) is real and often conflated, but it was about ESP perception of distant/current targets and was judged a failure by its own evaluation \u2014 it does not support a future-time-viewing machine.", "cites": ["S07", "S08"] }
  ],

  "provenance": [
    { "text": "Name-collision legitimacy laundering: verifying that \u201cLooking Glass\u201d is a real program confirms only the name, not the future-viewing function \u2014 the claim\u2019s strongest rhetorical asset.", "cites": ["S02", "S03"] },
    { "text": "Single-source chain: the device narrative traces to one witness lineage (Dan Burisch via Project Camelot) and its retellings; later retellings cite earlier retellings, not primary evidence (circular citation).", "cites": ["S11", "S14", "S20"] },
    { "text": "The witness\u2019s own \u201cconfirmation\u201d links point to rense.com and exopolitics.org \u2014 themselves paranormal sites, closing a self-referential sourcing loop.", "cites": ["S11"] },
    { "text": "Conflation drift: FOIA-released Project Stargate (remote-viewing) documents are sometimes shown as if they support a Looking Glass future-viewing device, though they concern ESP research, not machines or future timelines.", "cites": ["S07", "S08", "S10"] },
    { "text": "Unfalsifiable shields: rhetoric such as \u201crecords destroyed/classified\u201d or \u201ctimeline shifts erase evidence\u201d immunises the claim against archival falsification by design; treated here as rhetoric, not evidence.", "cites": ["S11", "S12"] },
    { "text": "Media feedback loop: entertainment programming and podcasts present the conflation as fact, and tertiary sources then cite each other \u2014 a closed loop broken only by returning to official primary records.", "cites": ["S14", "S15", "S16", "S17", "S18", "S19", "S20"] }
  ],

  "timeline": [
    { "date": "1961-02-03", "event": "Strategic Air Command begins the EC-135 \u201cLooking Glass\u201d airborne command post mission \u2014 a mirror of ground-based nuclear command-and-control.", "cites": ["S02", "S03"] },
    { "date": "1965-02-04", "event": "NYT reports the SAC flying command post has been airborne continuously for 4 years.", "cites": ["S04"] },
    { "date": "1972\u20131995", "event": "Project Stargate (USA/DoD remote-viewing / ESP research, grown from 1970s Stanford Research Institute work) operates; 1995 evaluation declares it a failure and it is terminated.", "cites": ["S07", "S08"] },
    { "date": "1998-10-01", "event": "EC-135 \u201cLooking Glass\u201d mission retired; the airborne command post role transfers to the Navy E-6B.", "cites": ["S02", "S03", "S06"] },
    { "date": "2007-12-10", "event": "Alleged confidential meeting between Project Camelot and Dan Burisch; page later states it produced intelligence about \u201cprobable future timelines\u201d (provenance of the wording).", "cites": ["S11"] },
    { "date": "2008-06-05", "event": "Burisch email adds \u201cLooking Glass Data\u201d claims (e.g., probable Pakistan\u2013India nuclear war) and cites rense.com/exopolitics.org as \u201cconfirmation.\u201d", "cites": ["S11"] },
    { "date": "2025\u20132026", "event": "The device narrative recirculates widely across podcasts/UFO media; UAPDrop acknowledges the claims \u201cremain unverified\u201d and George Knapp publicly calls the account a hoax.", "cites": ["S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19", "S20"] },
    { "date": "2026 (planned)", "event": "USAF begins acquiring \u201cLooking Glass-Next\u201d \u2014 the nuclear airborne command post mission, continuing under the same name.", "cites": ["S06"] }
  ],

  "summary": {
    "supporting": [
      { "text": "A real U.S. government program literally named \u201cLooking Glass\u201d did exist.", "cites": ["S02", "S03", "S06"] },
      { "text": "A real U.S. government psychic/remote-viewing program (Stargate) did exist and its records were declassified.", "cites": ["S07", "S08", "S10"] }
    ],
    "opposing": [
      { "text": "The real \u201cLooking Glass\u201d is a nuclear airborne command post with no observed future-viewing function.", "cites": ["S02", "S03", "S06"] },
      { "text": "No official, archival, FOIA, or primary record of a future-time-viewing device named \u201cLooking Glass\u201d exists in the searched public record.", "cites": ["S05", "S09", "S10"] },
      { "text": "The distinctive wording traces verbatim to a single, unverified whistleblower\u2019s account published by a paranormal-advocacy site, tied to a name collision and the Stargate conflation.", "cites": ["S11", "S12", "S13"] },
      { "text": "Project Stargate was an ESP program judged a failure and unrelated to any machine observing future timelines.", "cites": ["S07", "S08"] }
    ]
  },

  "verdict_change": [
    "A FOIA-released or declassified official document (or an official program history, budget line, or congressional record) naming \u201cProject Looking Glass\u201d as a future-timeline observation device, with purpose/location/contractor/dates/personnel, would shift this toward \u201csubstantiated.\u201d",
    "Corroborating archival material from NARA or the originating agency (memos, procurement records, photographs, test reports) \u2014 not third-party retellings.",
    "An independently verified, controlled, replicable demonstration or a verifiable attributable predictive output produced by the claimed system.",
    "Independent verification of the sole witness\u2019s identity/employment and a credible, verifiable account of the alleged 2007 meeting and the \u201cOrion Cube\u201d device.",
    "An explicit government confirmation or official denial specifically addressing the time-viewing claim.",
    "Conversely, a stronger, exhaustive archive/FOIA search across NARA, CIA/NSA/DIA reading rooms, and military/Congressional records confirming the name is used only for the airborne command post would reinforce \u201ccontradicted.\u201d"
  ],

  "unresolved_questions": [
    "Does any fully classified program matching the witness\u2019s description exist, unreachable by public search? (Absence of public records cannot prove a negative.)",
    "Can the sole witness\u2019s claimed credentials/employment (e.g., at S-4) be verified from primary records? Only third-hand negatives and a documented public hoax accusation were found.",
    "What is the complete declassified record set bearing the exact name \u201cProject Looking Glass\u201d? Public searches found only the airborne command post (S2).",
    "Does the primary text of the 1995 AIR remote-viewing evaluation exist and, if inspected in full, change the Stargate characterization?",
    "Is there any verifiable, independent account of the alleged December 2007 meeting or of the \u201cOrion Cube\u201d name\u2019s first appearance?"
  ],

  "source_quality": { "high": 4, "medium": 6, "low": 10 },

  "sources": [
    { "id": "S01", "title": "EC-135 Looking Glass \u2014 United States Nuclear Forces (C3I guide)", "publisher": "Federation of American Scientists (nuke.fas.org, hosting SAC/USSTRATCOM historical text)", "author": "FAS project staff (content from SAC/USSTRATCOM history)", "date": "page updated 2000-09-19 (mission facts 1961\u20131998)", "url": "https://nuke.fas.org/guide/usa/c3i/ec-135.htm", "source_type": "reference/archive page (official historical text)", "status": "challenges", "authority": "medium", "relevance": "direct", "independence": "independent", "verification": "inspected", "subclaim": "S2 / S1 / S4", "summary": "SAC began the \u201cLooking Glass\u201d airborne command post on 3 Feb 1961; nickname because it \u201cmirrored ground-based command, control, and communications\u201d; EC-135 Boeing 707 with a battle staff and airborne launch-control system transmitting launch codes to ICBMs; continuous 24/7 airborne alert ~29 years; retired 1 Oct 1998 and the mission passed to the Navy E-6B. No future-viewing content.", "paraphrase": "Shows the only documented official \u201cLooking Glass\u201d is the nuclear communications/command aircraft, challenging the device reading.", "strength": "Authoritative reference; directly inspected; consistent with current official reporting (S02/S06).", "limitation": "A non-government NGO reference (FAS), not an original declassified document; presence of the name confirms only the command-post function." },
    { "id": "S02", "title": "E-6B Airborne Command Post (ABNCP)", "publisher": "U.S. Strategic Command (stratcom.mil)", "author": "USSTRATCOM public affairs", "date": "undated page (accessed 2026)", "url": "https://www.stratcom.mil/DesktopModules/ArticleCS/Print.aspx?PortalId=8&ModuleId=1501&Article=960928", "source_type": "official government page", "status": "challenges", "authority": "high", "relevance": "direct", "independence": "independent", "verification": "search", "subclaim": "S2 / S1 / S4", "summary": "STRATCOM describes the E-6B airborne command post as the airborne command-and-control node for nuclear forces (successor to the EC-135 \u201cLooking Glass\u201d mission). Direct fetch was blocked by bot protection (Access Denied); represented by search-result material.", "paraphrase": "Official confirmation that the name/mission is command-and-control, not future viewing.", "strength": "Authoritative official military source.", "limitation": "Search-result material only; direct page fetch returned Access Denied." },
    { "id": "S03", "title": "Operation Looking Glass", "publisher": "Wikipedia (article incorporates U.S. government public-domain text; rev 1335105243)", "author": "Wikipedia editors", "date": "accessed 2026-08-17", "url": "https://en.wikipedia.org/wiki/Operation_Looking_Glass", "source_type": "encyclopedic (tertiary, partially government-derived)", "status": "challenges", "authority": "medium", "relevance": "direct", "independence": "derivative", "verification": "inspected", "subclaim": "S2 / S1 / S4", "summary": "Encyclopedic overview: \u201cLooking Glass\u201d was the SAC airborne command post with continuous airborne alert 1961\u20131990 and EC-135 service until 1998. Title and categories (e.g., \u201cUnited States command and control aircraft\u201d) directly verified.", "paraphrase": "Corroborates that Looking Glass was a command-and-control aircraft program.", "strength": "Reliable tertiary overview consistent with official histories; directly inspected metadata.", "limitation": "Tertiary compilation; body text not fully parsed this session." },
    { "id": "S04", "title": "SAC\u2019S FLYING HQ. IN THE AIR 4 YEARS; Backstop for Ground Center Observes Anniversary", "publisher": "The New York Times", "author": "NYT staff", "date": "1965-02-04", "url": "https://www.nytimes.com/1965/02/04/archives/sacs-flying-hq-in-the-air-4-years-backstop-for-ground-center.html", "source_type": "contemporaneous journalistic (primary document)", "status": "challenges", "authority": "high", "relevance": "direct", "independence": "independent", "verification": "search", "subclaim": "S2", "summary": "Contemporaneous 1965 news report confirming the SAC flying command post (Looking Glass) had been airborne for four years by 1965, consistent with the 1961 start. Attachment of the specific name is inferred (not verbatim in the cited title).", "paraphrase": "Contemporary mainstream press confirmation of the aircraft\u2019s command-and-control role.", "strength": "High-authority contemporaneous source.", "limitation": "Paywall blocked direct fetch; name not verbatim in title, so its use is inferred from context." },
    { "id": "S05", "title": "National Archives EC-135 \u201cLooking Glass\u201d photograph records (via third-party mirror)", "publisher": "National Archives and Records Administration (NARA; served via nara.getarchive.net mirror)", "author": "NARA/USAF photographers", "date": "Cold War era (exact dates not shown)", "url": "https://nara.getarchive.net/media/an-ec-135-stratolifter-aircraft-refuels-a-second-stratolifter-assuming-the-e0511c", "source_type": "official archival photographs (via mirror)", "status": "challenges", "authority": "medium", "relevance": "direct", "independence": "independent (archival); mirror = derivative access", "verification": "search", "subclaim": "S2", "summary": "NARA archival photographs of the EC-135 \u201cLooking Glass\u201d, with captions describing its role as SAC\u2019s backup command-and-control post.", "paraphrase": "Official archival provenance documents Looking Glass as a command aircraft.", "strength": "Official custodial provenance (NARA).", "limitation": "Accessed via third-party mirror; direct fetch blocked; exact record numbers not captured." },
    { "id": "S06", "title": "U.S. Air Force Moving to Take Navy\u2019s \u2018Looking Glass\u2019 Mission", "publisher": "Arms Control Association, Arms Control Today (Jan/Feb 2026)", "author": "Libby Flatoff", "date": "2026-01", "url": "https://www.armscontrol.org/act/2026-01/news-briefs/us-air-force-moving-take-navys-looking-glass-mission", "source_type": "policy-news article (respected arms-control journal)", "status": "challenges", "authority": "high", "relevance": "direct", "independence": "independent", "verification": "inspected", "subclaim": "S2", "summary": "\u201cLooking Glass\u201d ensures control of ICBM forces if land-based centers are attacked; on 24/7 alert 1961\u20131990; transferred to Navy E-6B in 1998; USAF announced \u201cLooking Glass-Next\u201d (from 9 Dec) citing Air & Space Forces Magazine and Breaking Defense.", "paraphrase": "Current official-status confirmation that Looking Glass is the nuclear airborne command post, name continuing into a new acquisition.", "strength": "High-authority policy journal; directly inspected; shows continuous official use of the name to 2026.", "limitation": "Covers only the nuclear command-and-control program; no future-viewing content." },
    { "id": "S07", "title": "The CIA Recruited \u2018Mind Readers\u2019 to Spy on the Soviets in the 1970s", "publisher": "HISTORY / A&E Television Networks (History.com)", "author": "Dave Roos", "date": "published 2018-10-17; updated 2025-06-30", "url": "https://www.history.com/articles/cia-esp-espionage-soviet-union-cold-war", "source_type": "mainstream history article (cites declassified CIA CREST documents)", "status": "challenges", "authority": "medium", "relevance": "direct", "independence": "independent", "verification": "inspected", "subclaim": "S3", "summary": "Project Star Gate operated 1972\u20131995; roots in 1970s Stanford Research Institute research; moved to Army Fort Meade under DIA funding; terminated 1995 after an independent evaluation (American Institutes for Research) declared it a failure \u2014 \u201cit remains unclear whether the existence of a paranormal phenomenon, remote viewing, has been demonstrated\u201d \u2014 and its outputs were \u201cvague and ambiguous\u201d with no \u201cactionable intelligence.\u201d", "paraphrase": "Real ESP research program, judged a failure, about perceiving distant/current targets \u2014 not a machine observing future timelines.", "strength": "Reputable mainstream source; directly inspected; consistent with the declassified primary documents it cites.", "limitation": "Secondary summary (the cited CREST PDFs not independently fetched); remote viewing is a different category from a future-viewing machine." },
    { "id": "S08", "title": "CIA uploads millions of classified documents on UFOs and psychic powers", "publisher": "The Independent (UK)", "author": "Independent staff", "date": "2017-01-18", "url": "https://www.the-independent.com/tech/cia-central-intelligence-agency-documents-classified-online-website-agency-a7533261.html", "source_type": "journalistic", "status": "contextual", "authority": "medium", "relevance": "indirect", "independence": "independent", "verification": "inspected", "subclaim": "S3", "summary": "News coverage of the CIA\u2019s declassification/online release of records including psychic/remote-viewing program files.", "paraphrase": "Corroborates that Stargate-era remote-viewing records are real and declassified.", "strength": "Corroborates the reality of the remote-viewing declassification; date verified directly.", "limitation": "Relevance is to the Stargate conflation, not to any Looking Glass device; full article text not parsed." },
    { "id": "S09", "title": "CIA Reading Room / CREST declassified collection on remote viewing (Stargate)", "publisher": "Central Intelligence Agency (cia.gov/readingroom)", "author": "n/a (records)", "date": "records 1970s\u20131995; digitized from 2017", "url": "https://www.cia.gov/readingroom", "source_type": "official declassified FOIA material (custodian)", "status": "contextual", "authority": "high", "relevance": "indirect", "independence": "independent", "verification": "unresolved", "subclaim": "S3", "summary": "CIA\u2019s public repository includes Stargate-era remote-viewing documents (e.g., the Gateway Report). Deep links redirect to the reading-room homepage this session, so not directly inspectable here. No document in the collection is known to name a \u201cLooking Glass\u201d future-viewing device \u2014 an explicitly non-exhaustive, properly-hedged negative.", "paraphrase": "The underlying declassification is genuine; the collection does not (on available knowledge) contain a Looking Glass time-viewing device.", "strength": "Official custodial FOIA material.", "limitation": "Not directly inspectable this session; the absence-based negative alone is not probative of falsification." },
    { "id": "S10", "title": "Psychic spies: how CIA used Scotland in bid to develop paranormal powers (Stargate files)", "publisher": "The Herald (Scotland)", "author": "Herald staff", "date": "circa 2017 (per context; not confirmed)", "url": "https://www.heraldscotland.com/news/15039661.Psychic_spies__how_CIA_used_Scotland_in_bid_to_develop_paranormal_powers/", "source_type": "journalistic", "status": "contextual", "authority": "medium", "relevance": "indirect", "independence": "independent", "verification": "search", "subclaim": "S3", "summary": "Report on declassified Stargate remote-viewing records.", "paraphrase": "Secondary coverage supporting that Stargate is a real, documented, declassified ESP program.", "strength": "Supports the Stargate-conflation premise.", "limitation": "Search-result material only; no Looking Glass connection." },
    { "id": "S11", "title": "Project Camelot \u2014 Timeline 1, variant 83: what may the future hold? (T1v83), relaying Dan Burisch\u2019s testimony", "publisher": "Project Camelot (Kerry Cassidy & Bill Ryan)", "author": "Project Camelot (meeting report) + Dan Burisch (testimony and 5 Jun 2008 email)", "date": "content: meeting 2007-12-10; email 2008-06-05", "url": "http://projectcamelot.org/t1v83.html", "source_type": "paranormal-advocacy website; whistleblower testimony page", "status": "contextual", "authority": "low", "relevance": "direct", "independence": "independent (origin node of the narrative)", "verification": "inspected", "subclaim": "S6 / S4 / S5", "summary": "States a confidential 10 Dec 2007 meeting with Dan Burisch produced \u201cintelligence data about probable future events\u2026 gained through a high-tech investigation into possible and probable future timelines\u201d (device: \u201cOrion Cube\u201d); that \u201cLooking Glass\u201d and \u201cStargate\u201d technology caused a future catastrophe; Burisch\u2019s 2008 email adds \u201cLooking Glass Data\u201d claims (probable Pakistan\u2013India nuclear war) and cites rense.com and exopolitics.org as \u201cconfirmation.\u201d The phrase \u201cprobable future timelines\u201d appears verbatim.", "paraphrase": "This is the documented origin of the claim\u2019s distinctive wording \u2014 a single witness\u2019s unverified testimony on a paranormal-advocacy site, with circular \u201cconfirmation.\u201d", "strength": "Directly inspected (verbatim phrase verified); precise origin/provenance of the wording.", "limitation": "Advocacy outlet; single-witness testimony; no documents/schematics; circular citations \u2014 evidence of the myth\u2019s origin, not of the program\u2019s existence." },
    { "id": "S12", "title": "Alleged S-4 Insider Recounts Project Looking Glass, Stargates, and a 2012 Risk Narrative", "publisher": "UAPDrop (UAP news/commentary; summarizing a \u201cPolarity\u201d YouTube session)", "author": "UAPDrop editorial", "date": "2025-11-14", "url": "https://www.uapdrop.com/l/view/b2jBYpazuFM.html", "source_type": "UAP-website commentary/article", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "derivative", "verification": "inspected", "subclaim": "S6 / S4 / S5", "summary": "Burisch describes Looking Glass as an \u201cEinstein\u2013Rosen bridge promoter\u201d at S-4; the article explicitly states \u201cthe claims remain unverified, and many conflict with established scientific models\u201d and that \u201cthere is no peer-reviewed record validating a terrestrial machine capable of stabilizing or viewing through [a wormhole].\u201d", "paraphrase": "Even a pro-UAP outlet concedes zero verification and zero peer-reviewed support for the device.", "strength": "Admission from within the paranormal ecosystem that the claim has no independent corroboration; directly inspected.", "limitation": "Itself part of the paranormal ecosystem (secondary commentary); concession informative but not authoritative on facts." },
    { "id": "S13", "title": "George Knapp Faces Scrutiny Over Dismissal of Dan Burisch\u2019s Claims", "publisher": "UAPDrop (summarizing the \u201cPsicoactivo Podcast\u201d episode)", "author": "UAPDrop editorial", "date": "2025-06-14", "url": "https://www.uapdrop.com/l/view/cYqm8-3UZ3Y.html", "source_type": "UAP-website commentary/article (reports George Knapp\u2019s public statement)", "status": "challenges", "authority": "low", "relevance": "direct", "independence": "derivative (reports Knapp\u2019s statement)", "verification": "inspected", "subclaim": "S4", "summary": "George Knapp \u2014 the journalist who broke the Bob Lazar Area 51 story \u2014 publicly calls Dan Burisch\u2019s account \u201ca fabrication\u2026 an elaborate hoax, involving staged photographs, falsified backgrounds, and orchestrated attempts to deceive,\u201d citing inconsistencies in credentials and personal history.", "paraphrase": "A mainstream investigative journalist documented fabrication behind the sole witness for the device claim.", "strength": "Specific, attributed counter-allegation against the sole witness; directly inspected.", "limitation": "Reported secondhand through UAPDrop; Knapp\u2019s underlying investigation not itself directly inspected; a name-mention in congressional records is noted by supporters but does not verify the claims." },
    { "id": "S14", "title": "Project Looking Glass: Timeline Shifts (episode)", "publisher": "The Swerve Podcast (via Podscan.fm episode directory)", "author": "podcast hosts (unnamed)", "date": "2026-02-04 (page metadata)", "url": "https://podscan.fm/podcasts/the-swerve-podcast-obscure-topics-conspiracy-theories/episodes/project-looking-glass-timeline-shifts", "source_type": "secondary (conspiracy podcast)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6", "summary": "A conspiracy podcast episode discussing the Looking Glass device and timeline shifts; proves the claim circulates as modern podcast lore, with no documentation cited.", "paraphrase": "Evidence the device narrative circulates as lore; not evidence of the device.", "strength": "Shows circulation.", "limitation": "Search-result/truncated descriptor only; no primary source." },
    { "id": "S15", "title": "ARCHIVE 022 \u2014 Project Looking Glass: Why Couldn\u2019t It See Past 2012?", "publisher": "Time Slipped podcast (via Poddtoppen)", "author": "podcast host (unnamed)", "date": "not displayed", "url": "https://poddtoppen.se/podcast/1827494312/time-slipped/the-future-went-silent-project-looking-glass", "source_type": "secondary (paranormal podcast)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6", "summary": "Podcast retelling that the device\u2019s view of the future stopped at 2012 \u2014 classic 2012-prophetic lore.", "paraphrase": "Retelling; 2012 framing ties to Camelot lore.", "strength": "Documents circulation/embellishment.", "limitation": "Search-result only; unverifiable." },
    { "id": "S16", "title": "Project Looking Glass: Timelines, Gray Aliens, And The Mandela Effect", "publisher": "\u201cAliens? Yes! But Maybe No\u201d UFO/UAP podcast (zeno.fm)", "author": "podcast hosts (unnamed)", "date": "not displayed", "url": "https://zeno.fm/podcast/aliens-yes-but-maybe-no-ufos-uaps-alien-mysteries/episodes/project-looking-glass-timelines-gray-aliens-and-the-mandela-effect/", "source_type": "secondary (UFO-lore podcast)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6", "summary": "UFO-lore retelling linking the device to timeline shifts, aliens, and the Mandela Effect.", "paraphrase": "Folklore retelling; circulation only.", "strength": "Shows entertainment circulation.", "limitation": "Search-result only; no primary basis." },
    { "id": "S17", "title": "Project Looking Glass: The GATE Program, Remote Viewing and Psychic Children", "publisher": "The Whole Rabbit podcast (via Poddtoppen)", "author": "podcast host (unnamed)", "date": "not displayed", "url": "https://poddtoppen.se/podcast/1457163771/the-whole-rabbit/project-looking-glass-the-gate-program-remote-viewing-and-psychic-children", "source_type": "secondary (paranormal podcast)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6 (and documents the S3-type conflation)", "summary": "Explicitly fuses Looking Glass with the GATE program, remote viewing, and \u201cpsychic children,\u201d merging the real Stargate conflation into the device lore.", "paraphrase": "Key example of the remote-viewing conflation occurring in media.", "strength": "Documents the conflation described in the framework.", "limitation": "Search-result only; proves nothing about underlying facts." },
    { "id": "S18", "title": "Project Looking Glass, Project Camelot Timeline convergence | Did 2012 \u2018BREAK\u2019 the timeline?", "publisher": "Apple Podcasts (episode listing)", "author": "podcast host (unnamed)", "date": "not displayed", "url": "https://podcasts.apple.com/us/podcast/project-looking-glass-project-camelot-timeline-convergence/id1797588645?i=1000742798162", "source_type": "secondary (conspiracy podcast; Project Camelot-related)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6", "summary": "Conspiracy retelling linking the device to Project Camelot and a 2012 \u201ctimeline break.\u201d", "paraphrase": "Clearly labelled conspiracy content tying the narrative to Camelot-era 2012 claims.", "strength": "Shows the Camelot/2012 lineage in circulation.", "limitation": "Search-result only." },
    { "id": "S19", "title": "PROJECT LOOKING GLASS: How Did Charlie Know He Was Going To Die? (Candace, Ep 290)", "publisher": "Candace podcast (transcript via happyscribe)", "author": "Candace (host)", "date": "not displayed", "url": "https://podcasts.happyscribe.com/candace/project-looking-glass-how-did-charlie-know-he-was-going-to-die-candace-ep-290", "source_type": "secondary (podcast; anecdotal)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "unresolved", "verification": "search", "subclaim": "S6", "summary": "Anecdotal retelling that \u201cCharlie\u201d foresaw his own death via the device; unverifiable, no named primary source.", "paraphrase": "Allegation-level anecdote; not evidence.", "strength": "Documents anecdote-level circulation.", "limitation": "Search-result only; unverifiable." },
    { "id": "S20", "title": "Cluster \u2014 repeated narrative across podcast/paranormal media (incl. The Reality Revolution; Journey to the Fringe; Smartly Uneducated; divinecosmos; ascensionglossary; a suno.com \u2018Yellow Cube\u2019 AI song)", "publisher": "Various independent podcast/paranormal media", "author": "various podcast hosts", "date": "2025\u20132026 (listings)", "url": "https://www.zeno.fm/podcast/aliens-yes-but-maybe-no-ufos-uaps-alien-mysteries/episodes/project-looking-glass-the-future-went-silent-project-looking-glass", "source_type": "secondary (podcast/paranormal media; search-result listings)", "status": "contextual", "authority": "low", "relevance": "indirect", "independence": "derivative", "verification": "search", "subclaim": "S6", "summary": "The same Burisch-derived narrative (Looking Glass, timeline shifts, Mandela Effect, 2012) is repeated across a large cluster of podcasts and sites, none offering primary documents \u2014 evidencing circular repetition down to an AI song.", "paraphrase": "Aggregate evidence of circular amplification with no primary source.", "strength": "Demonstrates breadth of circulation and absence of any primary source in the chain.", "limitation": "Search-result listings/snippets only; cited for circulation pattern, not content." }
  ]
};
